language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js:
  - "8.12.0"
script:
  - echo "Deploying!"
install:
  - yarn
after_success:
  - yarn build
  - firebase deploy --token $FIREBASE_TOKEN
