language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js:
  - "10.16.3"
script:
  - echo "Deploying!"
before_install:
  - yarn global add firebase-tools
install:
  - yarn
after_success:
  - yarn build
  - firebase deploy --token $FIREBASE_TOKEN
